In [20]:
# 1. What is a Python library? Why do we use Python libraries?

'''A Python library is a collection of pre-written code and functions that you can use to perform specific tasks without having to write that code yourself from scratch.
These libraries are designed to be reusable and often provide solutions to common problems or tasks in a particular domain.

We use Python libraries for several reasons:

Efficiency
Functionality
Specialization
Community Support
Compatibility'''

'A Python library is a collection of pre-written code and functions that you can use to perform specific tasks without having to write that code yourself from scratch.\nThese libraries are designed to be reusable and often provide solutions to common problems or tasks in a particular domain.\n\nWe use Python libraries for several reasons:\n\nEfficiency\nFunctionality\nSpecialization\nCommunity Support\nCompatibility'

In [21]:
# What is the ^ifference between Numpy array an^ List?

'''NumPy arrays are more suitable for numerical computations and large datasets due to their memory efficiency and optimized performance, 
while Python lists offer more flexibility for general-purpose data storage and manipulation with heterogeneous data types.'''

'NumPy arrays are more suitable for numerical computations and large datasets due to their memory efficiency and optimized performance, \nwhile Python lists offer more flexibility for general-purpose data storage and manipulation with heterogeneous data types.'

In [22]:
# 3. Find the shape, size and dimension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

import numpy as np
var = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("shape : ",var.shape)
print("size : ",var.size)
print("diamesion :",var.ndim)

shape :  (3, 4)
size :  12
diamesion : 2


In [23]:
# 4. Write python co^e to access the first row of the following array?

var_1 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

first_row = var_1[0]
print("first_row : ",first_row)

first_row :  [1 2 3 4]


In [24]:
# 5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?

var_2 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

element = var_2[2,3]
print("Element at the third row and fourth column:", element)

Element at the third row and fourth column: 12


In [25]:
# 7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?

random_matix = np.random.rand(3,3)

print(random_matix)

[[0.02804532 0.39702393 0.72172874]
 [0.55083895 0.96779825 0.02159358]
 [0.64306595 0.39061877 0.47783617]]


In [26]:
# 9. Write co^e to increase the ^imension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# # [9, 10, 11, 12]]

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

new_array = np.expand_dims(array, axis=0)

print(new_array)
print("shape:", new_array.shape)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
shape: (1, 3, 4)


In [31]:
# 10. How to transpose the following array in NumPy?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

transposed_array = np.transpose(array)

print("Original array:")
print(array)
print()
print("Transposed array:")
print(transposed_array)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [38]:
# 11
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Index wise multiplication

Index_wise_mult = A*B
print("index wise mult\n",Index_wise_mult)

#  Matrix multiplication
matrix_mult = np.dot(A, B.T)
print("matrix mult\n",matrix_mult)

# add both matrices
add = A+B
print("addition of matrices\n",add)

# subtract matrix b from a

sub = B-A
print("subtraction of B from A\n",sub)

# divide matrix b by a
division = np.where(A != 0, B / A, 0)
print("Division of matrix B by A:\n", division)

index wise mult
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
matrix mult
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
addition of matrices
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
subtraction of B from A
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Division of matrix B by A:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
